server:
  port: 8888
app:
  api-prefix: /api/v1

spring:
  cloud:
    gateway:
      default-filters:
        - StripPrefix=2
        - name: CircuitBreaker
          args:
            name: globalCircuitBreaker
            fallbackUri: forward:/fallback
      #        - name: RequestRateLimiter
      #          args:
      #            redis-rate-limiter.replenishRate: 10
      #            redis-rate-limiter.burstCapacity: 20
      #            redis-rate-limiter.requestedTokens: 1

      routes:
        - id: authentication-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/user/**

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/product/**

        - id: cart-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/cart/**

        - id: inventory-service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/inventory/**

        - id: order-service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/order/**

        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/payment/**

        - id: promotion-service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/promotion/**

        - id: notification-service
          uri: http://localhost:8088
          predicates:
            - Path=${app.api-prefix}/notification/**

resilience4j:
  circuitbreaker:
    instances:
      globalCircuitBreaker:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2000ms
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
#  ratelimiter:
#    instances:
#      globalRateLimiter:
#        limitForPeriod: 10
#        limitRefreshPeriod: 1s
#        timeoutDuration: 0