spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/user/**
          filters:
            - StripPrefix=2

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2

        - id: cart-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/cart/**
          filters:
            - StripPrefix=2

        - id: inventory-service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/inventory/**
          filters:
            - StripPrefix=2

        - id: order-service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/order/**
          filters:
            - StripPrefix=2

        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/payment/**
          filters:
            - StripPrefix=2

        - id: promotion-service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/promotion/**
          filters:
            - StripPrefix=2

        - id: notification-service
          uri: http://localhost:8088
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2

server:
  port: 8888
app:
  api-prefix: /api/v1