eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    configprops:
      enabled: true
    env:
      enabled: true
    loggers:
      enabled: true
  info:
    env:
      enabled: true