server:
  port: 8081
  servlet:
    context-path: /users

spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
    url: "jdbc:mysql://localhost:3306/toyland_user?createDatabaseIfNotExist=true"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
