server:
  port: 8081
  servlet:
    context-path: /user

spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
    url: "jdbc:mysql://localhost:3306/toyland_user?createDatabaseIfNotExist=true"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: user-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"