spring:
  application:
    name: order-service
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
    url: "jdbc:mysql://localhost:3306/toyland_order?createDatabaseIfNotExist=true"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8085
  servlet:
    context-path: /order

app:
  services:
    user: http://localhost:8081/user