spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://admin:12345678@localhost:27018/product-service?authSource=admin
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /product

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG
    com.toyland.product_service: DEBUG